version: '2'
services:
  product-mongodb:
    image: mongo:latest
    container_name: product-pricing-db
    ports:
      - "27017:27017"
  case-study:
    image: lowry-casestudy/casestudy:latest
    container_name: case-study-app
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - product-mongodb